# STUDENT PERFORMANCES
## Machine Learning project
## Team: Amadou and Jamie

* Analysis of student performances
* Features: 33 
* Data: 649

There are 2 different csv files in the data folder. One (student-port.csv) being the data set of the students that took the portugese language course and another (student-mat.csv) of the students that are taking the math course. There are 382 students that are taking both courses. 

More information about the dataset is in the data folder, labeled student.txt

In [1]:
# Importing the libraries to be used:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline 

from sklearn.preprocessing import StandardScaler  # It is important in neural networks to scale the date
from sklearn.model_selection import train_test_split  # The standard - train/test to prevent overfitting and choose hyperparameters
from sklearn.metrics import accuracy_score # 
import matplotlib.pyplot as plt 

In [2]:
df1 = pd.read_csv("data\student-por.csv",sep=";") #read file from different directory
df2 = pd.read_csv("data\student-mat.csv", sep = ";")
print(df1)
#df1.to_csv("port.csv") # made in to a csv after being made in to a table - easier to read compared to original excel file


    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health 

In [3]:
#Splitting the data accordingly
X = df1.iloc[:, :30]
y = df1.iloc[:, 32:]
X.dropna()
y.dropna()

G3
0    11
1    11
2    12
3    14
4    13
..   ..
644  10
645  16
646   9
647  10
648  11

[649 rows x 1 columns]

## Converting the specific features to binary to make it easier to work with
### school:  GP = 1 , MS = 0
### sex:  F = 1, M = 0
### address: U(urban) = 1, R(rural) = 0
### family size:  LE3 = 1, GT3 = 0
### pstatus: T(living together) = 1, A(living apart) = 0

In [4]:
def fixingfile(X):
    switch = {0: ("GP", "MS"), 1: ("F", "M"), 3: ("U", "R"), 4: ("LE3", "GT3"), 5:("T", "A"), 15:("yes","no"), 16:("yes","no"),
             17:("yes","no"), 18:("yes","no"), 19:("yes","no"), 20:("yes","no"), 21:("yes","no"), 22:("yes","no")}
    #ignore = ["age", "Medu", "Fedu","Mjob", "Fjob", 'reason', 'guardian','traveltime', 'studytime',
    #       'failures']
    #print(X.columns)
    #print(X.iloc[0,:])
    for column in range(len(X.columns)):
        if column not in switch:
            continue
        for i in range(len(X.iloc[:,column])):
           #print(X.iloc[i, column] == "U",X.iloc[i, column], switch[column])
            if X.iloc[i,column] == switch[column][0]:
                #print(X.iloc[i, column], switch[column][0])
                X.iloc[i,column] = 1
            elif X.iloc[i, column] == switch[column][1]:
                X.iloc[i,column] = 0
    X.drop(["Mjob", "Fjob", "reason", "guardian"], axis = 1, inplace=True) #Remove the ones with more than 1 and 0 answers
    print(X.shape)
    return X

In [5]:
X_fixed = fixingfile(X)
y = np.array(y) #changed to array to be easier to work with
X = np.array(X_fixed)

(649, 26)


# FROM here on out the markdown split up which model. Add cells according to which mark down. Here is the order
## 1. Linear Regression
## 2. Neutral Network 
## 3. SVM

# Multiple Linear Regression

In [6]:
#reshaping y to 2d
y_2d = y.reshape(y.shape[0], 1)
print("Checking y_2d is in 2d:", y_2d.shape)

Checking y_2d is in 2d: (649, 1)


In [7]:
N = y.shape[0]
print("Number of rows:", N)

Number of rows: 649


In [8]:
# Adding the column of ones infront of x
ones = np.ones((N, 1))
X_1 = np.hstack((ones, X))
print("X_1 shape:", X_1)
print("X_1 with ones: ", X_1)

X_1 shape: [[1.0 1 1 ... 1 3 4]
 [1.0 1 1 ... 1 3 2]
 [1.0 1 1 ... 3 3 6]
 ...
 [1.0 0 1 ... 1 5 6]
 [1.0 0 0 ... 4 2 6]
 [1.0 0 0 ... 4 5 4]]
X_1 with ones:  [[1.0 1 1 ... 1 3 4]
 [1.0 1 1 ... 1 3 2]
 [1.0 1 1 ... 3 3 6]
 ...
 [1.0 0 1 ... 1 5 6]
 [1.0 0 0 ... 4 2 6]
 [1.0 0 0 ... 4 5 4]]


In [9]:
def compute_cost(X_1, y_2d, w, N):
    # Write your code in place of ellipsis. Cost can be calculated using a single line of code.
    # Remember w is a vector here.
    
    # TODO Q07 - Taken from hw
    # Write the cost function
    #ISSUES: X AND Y ARE NOW 2D ARRAYS
    cost = sum((y_2d- (np.dot(X_1, w)))**2)/(2*N)
    
    return cost[0]

In [10]:
def gradient_descent(X_1, y_2d, learning_rate, w, N, num_iters):
    # In place of ellipsis, write the updated value of w0 in temp0 and of w1 in temp1
    # TODO Q08
    # Finish the gradient descent function
    
    for i in range(num_iters):
        # derivative vector is given by : X_train.Transpose *  (( X_train * w)- y ) 
        slope = np.dot(X_1, w)
        der_vector = np.dot(X_1.T,(slope - y_2d))
        w = w - (learning_rate * (1/N)) * der_vector
       
        
        if(i % 100 == 0):
            # In place of ellipsis, call the cost you just coded above
            cost = compute_cost(X_1, y_2d, w, N)
            # You can uncomment print statements below to see how cost changes, 
            # but please make sure you put prints in comments before submission
            #print("Cost")
            #print(cost)
             
    return w 

In [11]:
w_testcase = np.zeros((X.shape[1]+1,1))
g = gradient_descent(X_1, y_2d, 0.0049, w_testcase, N, 1000)
#print(g)
print("g[0]: ", g[0][0])

g[0]:  0.2074664653929119


In [12]:
def multiple_linear_reg_model_gda(X_1, y_2d, learning_rate, N, num_iters):
    #initialize the values of parameter vector w. It should be a column vector of zeros of dimension(d+1,1)
    # TODO 09 
    # Complete the function
    w = np.zeros((X_1.shape[1],1))
    
    # Calculate the initial cost by calling the function you coded above.
    initial_cost = compute_cost(X_1, y_2d, w, N)
    
    # Calculate the optimized value of gradients by calling the gradient_descent function coded above
    w = gradient_descent(X_1, y_2d, learning_rate, w, N, num_iters)
    
    # Calculate the cost with the optimized value of w0 and w1 by calling the cost function.
    final_cost = compute_cost(X_1, y_2d, w, N)

    return w, initial_cost, final_cost

In [13]:
learning_rate = 0.0049
num_iters = 100
results = multiple_linear_reg_model_gda(X_1, y_2d, learning_rate, N, num_iters)
print("w: ", results[0], "\ninitial cost: ", results[1], "\nfinal cost: ", results[2])

w:  [[0.06223085015486552]
 [0.21897598917388655]
 [0.12110629798834996]
 [0.5362713736451512]
 [0.1361817648876116]
 [0.05342830790297382]
 [0.05258571165888326]
 [0.3460226622118291]
 [0.3041147516832605]
 [0.003368032959320358]
 [0.3279441153101551]
 [-0.33352699521058427]
 [-0.015925643000496054]
 [0.06916759937467512]
 [-0.022596248827467892]
 [0.059942963116116084]
 [0.048255030939220116]
 [0.20334354059080167]
 [0.10836578185126233]
 [-0.05772311858928713]
 [0.2317441851385428]
 [-0.019640111414854323]
 [-0.006815584519605268]
 [-0.15612160129671793]
 [-0.13102553307655435]
 [-0.039118901768639316]
 [-0.05433619249045]] 
initial cost:  76.08705701078583 
final cost:  4.446168806722196


# Neutral Network
## some of these code are taken from hw6 as I deemed them essential 

In [14]:
X_scale = StandardScaler()
X_fit = np.array(X_scale.fit_transform(X))

In [15]:
#Split the data into training and test set.  60% training and %40 test
X_train, X_test, y_train, y_test = train_test_split(X_fit, y, test_size=0.4)

In [16]:
#Code copied from hw6, but edited to match our y values
def convert_y_to_vect(y):
    y_vect = np.zeros((len(y), 20))
    for i in range(len(y)):
        y_vect[i, y[i]] = 1
    return y_vect

In [17]:
y_v_train = convert_y_to_vect(y_train)
y_v_test = convert_y_to_vect(y_test)
print("Testing training set shape: ",y_v_train.shape)
print("Testing testing set shape: ",y_v_test.shape)

Testing training set shape:  (389, 20)
Testing testing set shape:  (260, 20)


In [18]:
# Sigmoid activation function - depends on whether we want to use it or not
def f(z):
    return 1 / (1 + np.exp(-z))


def f_deriv(z):
    return f(z) * (1 - f(z))

In [19]:
def calculate_out_layer_delta(y, a_out, z_out):
    # delta^(nl) = -(y_i - a_i^(nl)) * f'(z_i^(nl))
    return -(y-a_out) * f_deriv(z_out) 


def calculate_hidden_delta(delta_plus_1, w_l, z_l):
    # delta^(l) = (transpose(W^(l)) * delta^(l+1)) * f'(z^(l))
    return np.dot(np.transpose(w_l), delta_plus_1) * f_deriv(z_l)